import Head from 'next/head';
import tw from 'twin.macro';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App With Tailwind & Emotion</title>
        <meta name="description" content="Generated by create next app with tailwind & emotion" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main css={tw`flex flex-col justify-center items-center p-1.5 min-h-screen`}>
        <div css={tw`text-center font-bold`}>Create Next App With Emotion & Tailwind & Typescript</div>
      </main>
    </>
  );
}
